jenkins:
  url: http://eid-jenkins02.dmz.local
  adminAddress: Jenkins &lt;utvtest@difi.no&gt;

jira:
  url: http://jira.difi.local
  issues:
    bug: 11
  fields:
    sourceCodeRepository: 12380
  statuses:
    open: 1
    inProgress: 3
    readyForVerification: 10717
    codeApproved: 10005
    codeReview: 10012
    manualVerification: 10009
    manualVerificationOk: 10010
    manualVerificationFailed: 10917
  transitions:
    start: 371
    readyForCodeReview: 391
    startVerification: 291
    cancelVerification: 401
    resumeWork: 301
    approveCode: 321
    resumeWorkFromApprovedCode: 331
    startManualVerification: 311
    approveManualVerification: 51
    failManualVerification: 61
    failStagingDeploy: 451
    retryManualVerificationFromSuccess: 441
    retryManualVerificationFromFailure: 421
    closeWithoutStaging: 361
    close: 341

crucible:
  url: http://fisheye.difi.local:8060
  projectKey: CR

environments:
  pipeline-verification:
    mavenRepository: VerificationLocal
    dockerRegistry: VerificationLocal
  pipeline-staging:
    mavenRepository: StagingLocal
    dockerRegistry: StagingLocal
  pipeline-production:
    mavenRepository: ProductionLocal
    dockerSwarm: pipeline
  pipeline:
    mavenRepository: ProductionLocal
    dockerSwarm: pipeline
  eid-verification:
    mavenRepository: VerificationLocal
    dockerSwarm: eid-verification
  eid-staging:
    mavenRepository: StagingEvry
    puppetMaster: eid-staging
  eid-production:
    mavenRepository: ProductionEvry
    dockerRegistry: ProductionLocal
  statistics-verification:
    mavenRepository: VerificationLocal
    dockerRegistry: VerificationLocal
  statistics-staging:
    mavenRepository: StagingLocal
    dockerSwarm: statistics-staging
  statistics-production:
    mavenRepository: ProductionLocal
    dockerSwarm: statistics
  statistics:
    mavenRepository: ProductionLocal
    dockerSwarm: statistics
  oidc-provider-verification:
    mavenRepository: VerificationLocal
    dockerRegistry: VerificationLocal
  oidc-provider-staging:
    mavenRepository: StagingLocal
    dockerSwarm: oidc-provider-staging
  oidc-provider-production:
    mavenRepository: ProductionLocal
    dockerSwarm: oidc-provider
  oidc-provider:
    mavenRepository: ProductionLocal
    dockerSwarm: oidc-provider
  public-delivery:
    dockerRegistry: ProductionPublic
  local-delivery:
    dockerRegistry: ProductionLocal

maven:
  repositories:
    VerificationLocal:
      address: http://nexus:8081/repository/maven-verification
      credentialsId: nexus
    StagingLocal:
      address: http://nexus:8081/repository/maven-staging
      credentialsId: nexus
    ProductionLocal:
      address: http://nexus:8081/repository/maven-production
      credentialsId: nexus
    StagingEvry:
      address: http://eid-artifactory.dmz.local:8080/artifactory/libs-release-local
      credentialsId: artifactory-publish
    ProductionEvry:
      address: http://eid-artifactory.dmz.local:8080/artifactory/production-evry
      credentialsId: artifactory-publish

docker:
  host: tcp://eid-jenkins02.dmz.local:2376
  registries:
    VerificationLocal:
      address: eid-jenkins02.dmz.local:8083
      apiUrl: http://eid-jenkins02.dmz.local:8080/repository/docker-verification
      credentialsId: nexus
    StagingLocal:
      address: eid-jenkins02.dmz.local:8082
      apiUrl: http://eid-jenkins02.dmz.local:8080/repository/docker-stage
      credentialsId: nexus
    ProductionLocal:
      address: eid-jenkins02.dmz.local:8081
      apiUrl: http://eid-jenkins02.dmz.local:8080/repository/docker
      credentialsId: nexus
    StagingPublic:
      address: docker.io/difi
      credentialsId: dockerHub
    ProductionPublic:
      address: docker.io/difi
      credentialsId: dockerHub
  swarms:
    pipeline-verification:
      registry: VerificationLocal
    pipeline:
      host: eid-jenkins02.dmz.local
      user: jenkins
      sshKey: ssh.git.difi.local
      registry: ProductionLocal
    eid-verification:
      host: eid-test01.dmz.local
      user: jenkins
      sshKey: ssh.git.difi.local
      registry: StagingLocal
    statistics-staging:
      host: eid-test-docker01.dmz.local
      user: jenkins
      sshKey: ssh.git.difi.local
      registry: StagingLocal
    statistics:
      host: eid-prod-docker01.dmz.local
      user: jenkins
      sshKey: ssh.git.difi.local
      registry: ProductionLocal
    oidc-provider-verification:
      registry: VerificationLocal
    oidc-provider-staging:
      host: eid-test-oidc-provider.dmz.local
      user: jenkins
      sshKey: ssh.git.difi.local
      registry: StagingLocal
    oidc-provider:
      host: eid-oidc-provider.dmz.local
      user: jenkins
      sshKey: ssh.git.difi.local
      registry: ProductionLocal
    public-delivery:
      registry: ProductionPublic
    local-delivery:
      registry: ProductionLocal

puppet:
  masters:
    eid-staging:
      host: eid-puppetmaster.dmz.local
      user: jenkins
      sshKey: ssh.git.difi.local

ssh:
  knownHosts:
    - github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
    - git.difi.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG4VYlrX7IlRq+O1lokYTp1oYe7vsIPAmm9uhDec2TVvCkPnSeNhJq9iCyRYCaaCxZLRfUjQdCNc6NvNyXdZb6k=
    - eid-gitlab.dmz.local ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEApaqpEGnJ/z4Ur+bgHhnpYCBCdyPuDMVxUplgVPaUTjCLEiEioU+LgZsr04pX6s9sqHbH+0+ggAizxpXQZJ4AOgyeSCwtZNpqX3jXdXMCXqjQgDY/Pxu1vi91PucNK8B4lwkrhed9Ze8iCzdKY5w1NZDpB6Auc+UL2I0HJNDIlrxenYXdqtK6udLyEv1eViGCOIPY1YJ1SjVxMWv2G4itdJDQrOqe6U3p5Ph3P810rtIh/q4Z1PbdS98Jvh3VewdMpQjqPSTskn+EsnlEGJf8vvJmsVsRol1X5bmU/mxIXsaySzPmKdH34hQFzdejdjp83FYRffV0OYhL8Ur9ZU+Apw==
    - eid-jenkins02.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBC1UgDT1mm3EJ2w90x2zeEVzxdFPxcqkp+a0N6+0WLgNgTLVFRt2/hSM48VfCaFQaOzVw8PfxVSIHtuunFry1qo=
    - eid-jenkins03.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLLtI8VjTpcgoKoer2t8K3eFvT6/23ajAsT6U4tk5TaqDMteJzrE/p8v+XzcrMrWPaqdxZV4h+uLYv5VtyDeZRU=
    - eid-test-oidc-provider.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMzEIRiGtC0hPPq9mDXqw+TCye5gzFGI8mouaeIMRaRwHhI5rh1PZ39SbzzOgpAT2hW8YRkwBYMN5qCZnfJ0KCI=
    - eid-test-oidc-klient.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBhqhkaSU8DLfbTzM1nVZFIciooTYIluNkRdTznEqZGUP3I6YYW9OTQDP/8cgWhv22l3lVmFLSrsxgf0IsBXI1I=
    - eid-oidc-provider.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLtZOtk+k07ET+seli2lXbKYSaCae0wnP/OyA+o84epOGuGU+zT69Jqo0Bugll/It1xJ8C+IJthd9XfnlAx4tOA=
    - eid-test01.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKjTYi07cANNMTe0SwFEk6bq5VIp1inb2k1bUnL3bodhwUny9yG1amchjgvgmTol84niKETBOYVnGBqDh9UUNIs=
    - eid-test-docker01.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIYFaQAAGYZMGs2nuTF1kSvU43HQk759zCbU4SMKr1je08/6AfgRmQ8MwVGb+glKplAOP4mD1La92Ltj2DjamNo=
    - eid-prod-docker01.dmz.local ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCQ1MR4RdFoP7lNSI6sJW4b1p6+6GrCl5mUTQ4Fyqhsj7e8IFKyZS5/cUqhgu+z69y0d+5ZdZoy9gcnx1iDZCW0=
