jobs:
  jenkins-pipeline:
    repository: git@github.com:difi/jenkins-pipeline
    sshKey: ssh.github.com
  jenkins-docker:
    repository: git@github.com:difi/jenkins-docker
    sshKey: ssh.github.com
  kontaktregister-statistikk-klient:
    repository: git@github.com:difi/kontaktregister-statistikk-klient
    sshKey: ssh.github.com
  idporten-innlogging-statistikk-klient:
    repository: git@github.com:difi/idporten-innlogging-statistikk-klient
    sshKey: ssh.github.com
  idporten-oidc-client:
    repository: git@github.com:difi/idporten-klient-oidc.git
    sshKey: ssh.github.com
  poc-statistics:
    repository: git@github.com:difi/poc-statistics
    sshKey: ssh.github.com
  eid-oidc-provider:
    repository: git@git.difi.local:eid-oidc-provider
    sshKey: ssh.git.difi.local
  minid-on-the-fly:
    repository: git@git.difi.local:minid-on-the-fly
    sshKey: ssh.git.difi.local
  eid-common-resilience:
    repository: git@git.difi.local:eid-common-resilience.git
    sshKey: ssh.git.difi.local
  eid-common:
    repository: git@git.difi.local:eid-common.git
    sshKey: ssh.git.difi.local
  krr:
    repository: git@git.difi.local:krr.git
    sshKey: ssh.git.difi.local
  idporten:
    repository: git@git.difi.local:idporten.git
    sshKey: ssh.git.difi.local
  idporten-admin:
    repository: git@git.difi.local:idporten-admin.git
    sshKey: ssh.git.difi.local
  idporten-authlevel:
    repository: git@git.difi.local:idporten-authlevel.git
    sshKey: ssh.git.difi.local
  idporten-app-dpi-reklame:
    repository: git@git.difi.local:idporten-app-dpi-reklame.git
    sshKey: ssh.git.difi.local
  idporten-bankid:
    repository: git@github.com:difi/idporten-bankid.git
    sshKey: ssh.github.com
  idporten-bankidmobil:
    repository: git@github.com:difi/idporten-bankidmobil.git
    sshKey: ssh.github.com
  idporten-minid-updater:
    repository: git@github.com:difi/idporten-minid-updater.git
    sshKey: ssh.github.com
  idporten-pinkoder:
    repository: git@git.difi.local:idporten-pinkoder.git
    sshKey: ssh.git.difi.local
  dine-kontaktopplysninger:
    repository: git@git.difi.local:dine-kontaktopplysninger.git
    sshKey: ssh.git.difi.local
  dsf-gateway:
    repository: git@git.difi.local:dsf-gateway.git
    sshKey: ssh.git.difi.local
  eid-level1-poc:
    repository: git@git.difi.local:eid-level1-poc.git
    sshKey: ssh.git.difi.local
  eid-system-tests:
    repository: git@git.difi.local:eid-system-tests.git
    sshKey: ssh.git.difi.local
  serviceprovider-api-tests:
    repository: git@git.difi.local:serviceprovider-api-tests.git
    sshKey: ssh.git.difi.local
  eid-pipeline-branch:
    repository: git@git.difi.local:eid-pipeline-branch.git
    sshKey: ssh.git.difi.local
  eid-pipeline:
    repository: git@git.difi.local:eid-pipeline.git
    sshKey: ssh.git.difi.local
  eid-pipeline-config:
    repository: git@git.difi.local:eid-pipeline-config.git
    sshKey: ssh.git.difi.local
  eidas:
    repository: git@git.difi.local:eidas.git
    sshKey: ssh.git.difi.local
  eidas-proxies:
    repository: git@github.com:difi/eidas-proxies.git
    sshKey: ssh.github.com
  eid-maintenance:
    repository: git@git.difi.local:eid-maintenance.git
    sshKey: ssh.git.difi.local
  eid-docker-maintenance:
    repository: git@git.difi.local:eid-docker-maintenance.git
    sshKey: ssh.git.difi.local
  eid-web:
    repository: git@git.difi.local:eid-web.git
    sshKey: ssh.git.difi.local
  puppet_modules:
    repository: git@eid-gitlab.dmz.local:puppet/puppet_modules
    sshKey: ssh.git.difi.local
  puppet_modules_ext:
    repository: git@eid-gitlab.dmz.local:puppet/puppet_modules_ext
    sshKey: ssh.git.difi.local
  puppet_hiera:
    repository: git@eid-gitlab.dmz.local:puppet/puppet_hiera
    sshKey: ssh.git.difi.local
  idporten-testsp:
    repository: git@git.difi.local:idporten-testsp.git
    sshKey: ssh.git.difi.local
  dpi-registration:
    repository: git@git.difi.local:dpi-registration.git
    sshKey: ssh.git.difi.local
  eid-database:
    repository: git@git.difi.local:eid-database.git
    sshKey: ssh.git.difi.local
  mf-gateway:
    repository: git@github.com:difi/mf-gateway.git
    sshKey: ssh.github.com
  eid-eventlog-api:
    repository: git@git.difi.local:eid-eventlog-api.git
    sshKey: ssh.git.difi.local
  minprofil:
    repository: git@git.difi.local:minprofil.git
    sshKey: ssh.git.difi.local
  eid-serviceprovider:
    repository: git@git.difi.local:eid-serviceprovider.git
    sshKey: ssh.git.difi.local
  brukerprofil-web:
    repository: git@github.com:difi/idporten-brukerprofil
    sshKey: ssh.github.com
  idporten-authorization-api:
    repository: git@git.difi.local:idporten-authorization-api.git
    sshKey: ssh.git.difi.local
  eid-logwriter:
    repository: git@github.com:difi/eid-logwriter
    sshKey: ssh.github.com 
  krr-oppslagstjenesten-rest:
    repository: git@github.com:difi/krr-oppslagstjenesten-rest
    sshKey: ssh.github.com   
  eid-serviceprovider-admin:
    repository: git@git.difi.local:eid-serviceprovider-admin.git
    sshKey: ssh.git.difi.local
  sp-web:
    repository: git@github.com:difi/sp-web
    sshKey: ssh.github.com
  maskinporten:
    repository: git@github.com:difi/maskinporten
    sshKey: ssh.github.com
  altinn-gateway:
    repository: git@github.com:difi/altinn-gateway
    sshKey: ssh.github.com
  idporten-tokenexchange:
    repository: git@github.com:difi/idporten-tokenexchange
    sshKey: ssh.github.com