#!/usr/bin/env sh

echo
echo "Pausing service 'jenkins' and removing existing configuration..."
echo
docker service update pipeline_jenkins --config-rm pipeline-jobs --config-rm pipeline-config --replicas 0 || exit 1
echo
echo "Pausing service 'jenkins-slave' and removing existing configuration..."
echo
docker service update pipeline_jenkins-slave --config-rm pipeline-config --replicas 0 || exit 1
echo
echo "Replacing configuration..."
echo
docker config rm pipeline-jobs
docker config rm pipeline-config
docker config create pipeline-jobs /jobs.yaml || exit 1
docker config create pipeline-config /config.yaml || exit 1
echo
echo "Updating service 'jenkins' with new configuration and resuming..."
echo
docker service update pipeline_jenkins --config-add source=pipeline-jobs,target=/jobs.yaml --config-add source=pipeline-config,target=/config.yaml --replicas 1 || exit 1
echo
echo "Updating service 'jenkins-slave' with new configuration and resuming..."
echo
docker service update pipeline_jenkins-slave --config-add source=pipeline-config,target=/config.yaml --replicas 2 || exit 1
